format = """
$os\
$directory\
$git_branch\
$git_status\
$python\
$fill\
\n$character\
"""

right_format = """
$cmd_duration
$lua
$rust
$time
"""

[os]
format = "[$symbol](bold white)"
disabled = false

[os.symbols]
Macos = " " #リンゴのicon
Ubuntu = " " #Ubuntuのicon

[directory]
truncation_length = 6
truncation_symbol = ' ' # nf-fa-folder_open
truncate_to_repo = false
home_symbol = ' ~' # nf-costum-home
style = 'fg:#7aa2f7'
read_only = ' 󰌾 ' # nf-md-lock
read_only_style = 'fg:#f7768e'
format = '[$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = ' ' # nf-fa-github_alt, nf-fa-code_fork
truncation_length = 4
truncation_symbol = ''
style = 'fg:#7aa2f7'
format = '[ $symbol$branch(:$remote_branch)]($style)' # nf-pl-left_soft_divider

[git_status]
style = 'fg:#e0af68'
conflicted = '='
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕'
up_to_date = '✓'
untracked = '?'
stashed = '$'
modified = '!${count}'
renamed = '»'
deleted = '✘'
format = '([\[$all_status$ahead_behind\]]($style))  '

[python]
symbol = ' ' # nf-dev-python
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)  '
pyenv_version_name = false
style = 'fg:#999999'

[fill]
symbol = '─'
style = 'blue'

[character]
success_symbol = ' [❯](bold #9ece6a)'
error_symbol = ' [❯](bold red)'

[cmd_duration]
min_time = 1
style = 'fg:#e0af68'
format = "[   $duration]($style)" # nf-pl-right_soft_divider, nf-mdi-clock

[lua]
symbol = "" # nf-seti-lua
format = '[  $symbol $version](blue)' # nf-pl-right_soft_divider

[rust]
symbol = "" # nf-dev-rust
format = '[  $symbol $version](red)' # nf-pl-right_soft_divider

[time]
disabled = false
style = 'fg:#73daca'
format = '[   $time]($style)' # nf-pl-right_soft_divider, nf-fa-clock_o
time_format = '%T'
utc_time_offset = '+9'
